name: "server"

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server.yaml"

defaults:
  run:
    working-directory: server

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: "install"
        run: yarn install --frozen-lockfile
      - name: "test"
        run: yarn test
